### ISSUE TITLE
Issue in Injection signal

### ISSUE THREAD

**Issue by WirelessHubMaster** [noisymime/speeduino#195] opened 2019-02-05 06:45 UTC
I have tried to map the pins  to the MEGA 2560 as per the case 3 (0.4 shield), kept the code the same as the original. pinInjector1 signal is being displayed, the other signals are at 0. I've tried everything, from resetting the Board to uploading and changing the wires. It still isn't working. Note: I'm Using Analog Discovery as my oscilloscope.

![20190205_120139](https://user-images.githubusercontent.com/47134622/52256981-da60d100-293e-11e9-9ebf-132a0b760524.jpg)

**Comment by noisymime** [comment] 2019-02-05 08:57
Post your tune please. Very likely this is something misconfigured within there.

**Comment by WirelessHubMaster** [comment] 2019-02-06 06:42
Is this the tune you asked for? Please let me know if you want anything else
[Injectortrial1.zip](https://github.com/noisymime/speeduino/files/2835118/Injectortrial1.zip)

**Comment by noisymime** [comment] 2019-02-06 21:37
Your tune is set for 1 cylinder / 1 injector, so none of the other injector outputs will be active. This is the normal, expected behaviour.

**Comment by WirelessHubMaster** [comment] 2019-02-07 06:02
I'm going for 1 Cylinder/ 4 Injectors as the main project. I've added the injection timing cases in an loop(subcases) , the signals should be present as 1, 1a, 1b, 1c. Also how and where should i make changes in speeduino.ini to change the phase of the injector 1 and the remaining three pulses so that the three signals ( 1a, 1b,1c ) that i'm trying to implement have a delay/Phase shift from the main Injector1 pulse ?

**Comment by noisymime** [comment] 2019-02-07 06:16
Single cylinder with 4 injectors is certainly a unique setup!
So you want all 4 injector outputs to fire at defined intervals.

If so, you're probably best to configure it as a 4 cylinder engine, then change the timing between the pulses by setting it as odd-fire and defining the angles you want.

**Comment by WirelessHubMaster** [comment] 2019-02-07 16:56
Sorry for the confusion. It's a single cylinder with single injector with multiple timing (4 pulses) for fuel injection. I'm currently unable to configure it from the .ini file, hope you can guide me through for the above.

**Comment by noisymime** [comment] 2019-02-08 05:29
Have you tried increasing the number of squirts setting?

**Comment by WirelessHubMaster** [comment] 2019-02-08 07:29
Doesn't allow multiple squirts for single cylinder/Single Injector. Tunerstudio gives a warning.

**Comment by Magnum828** [comment] 2019-02-17 13:42
This is also a problem for me, I think the calculation should be that you can't alternate e.g. 2 cyl with 3 squirts because that isn't providing a whole number. But 1 cyl 1 inj and 2 squirts per cycle should be possible!

**Comment by brunob45** [comment] 2019-10-17 20:24
The {number of squirts} value sent to speeduino is not the number we see, but instead {number of cylinders} / {number of squirt}. 1 cylinder and 4 squirts would mean a value of 1/4=0.25: That number must be an integer, so this configuration is invalid. This is a limitation hardcoded into TunerStudio, as Megasquirt was coded this way. Unfortunately, your setup won't be possible as long as we're using the default Engine Constants panel.

**Comment by noisymime** [comment] 2022-10-03 04:22
This limitation was removed and the issue resolved with 8886d3dbd75dbbcd983795a6705d9fae0a813242

**Closed by noisymime** 2022-10-03 04:22 UTC
