### ISSUE TITLE
Air Conditioning Control issue in ” closed + openloop  STEPPER idle “mode

### ISSUE THREAD

**Issue by nuosu** [noisymime/speeduino#1166] opened 2024-01-22 07:31 UTC
In the Air Conditioning Control function, the idle up feature does not work in ” OLCL STEPPER mode“.

**Comment by turboedge** [comment] 2024-01-22 15:52
Can confirm this does not work in open loop either. Step gauge does not change when AC input changes. It would also be helpful if the change field could accept negative values as I run my table backward, eg more steps=more closed=slower idle.

**Comment by turboedge** [comment] 2024-02-12 22:28
> 
Well I feel silly. It would seem the firmware that I had was older than I thought, and this does work in open-loop stepper mode now. Apologies

**Comment by noisymime** [comment] 2024-02-19 22:35
This appears to be working fine in my testing. I am seeing the IAC Load value increasing by the expected amount when the A/C Request Input goes active. 

Can you post your tune and I see if there's anything that stands out, but this does appear to be operating as intended. What version of the code are you testing with?

**Comment by noisymime** [comment] 2024-05-30 00:02
Closing this as I cannot reproduce the issue. Please feel free to re-open with a log/tune if you're still seeing it.

**Closed by noisymime** 2024-05-30 00:02 UTC
