### ISSUE TITLE
Duty cycle stops att 24.5

### ISSUE THREAD

**Issue by KylTony** [noisymime/speeduino#146] opened 2018-06-24 23:13 UTC
4squirts alternating basictrigger v8 2injectors.
Duty stops att 24.5% ????? and it goes lean.
Max duty is set to 98%
Swapt to MS2 and it goes upp to 95% att full throttle.

**Comment by noisymime** [comment] 2018-06-25 00:11
Please post tune and log files of this issue occurring.

**Comment by KylTony** [comment] 2018-06-25 06:28
[Duty.zip](https://github.com/noisymime/speeduino/files/2131954/Duty.zip)

**Comment by KylTony** [comment] 2018-06-25 06:35
[Duty.zip](https://github.com/noisymime/speeduino/files/2131960/Duty.zip)

**Comment by KylTony** [comment] 2018-06-25 06:36
ops bigg fingers

**Comment by lsdlsd88** [comment] 2018-06-25 18:11
could it be due to 4 squirt per cycle screws up some DC% calculation? 24.5x4 is 98...

**Comment by noisymime** [comment] 2018-06-25 23:10
@lsdlsd88 This was my first thought as well. I'll be looking at this type of thing shortly.

**Comment by kimdrummel** [comment] 2018-07-18 19:53
I can confirm this problem as well. Tried it out today. When selecting 1 squirt/cycle, you get the full duty. But when selecting 2 squirts, you get 50%, 4 squirts 25% etc. Using Tony's tune.

**Comment by lsdlsd88** [comment] 2018-07-18 19:58
Yes but does 50% for 2 squirts actually means saturating injectors?
I mean if the issue is only in representing real DC% or it effectively cuts the squirt duration in half (you'll get a very lean condition)

**Comment by KylTony** [comment] 2018-07-18 20:13
![received_1771204912974452](https://user-images.githubusercontent.com/12009933/42905240-b893ba7a-8ad7-11e8-8aeb-bcb12e0637f3.jpeg)

**Comment by kimdrummel** [comment] 2018-07-22 08:00
Tested this on the bench with older firmwares. And up until the February release, everything works fine. But when loading the April release, the duty and pulsewidth is starting to get limited. On the February release, i get a full 100% duty cycle and about 7ms opening time max. (Req fuel is around 8) But when running the April Firmware, it gets limited to 25%, followed by a limiting of the pulsewidth as well.

**Comment by noisymime** [comment] 2018-10-02 01:05
Just following up on this, the issue should've been resolved a little while back. Are you able to confirm whether this is resolved with the current release?

**Comment by KylTony** [comment] 2018-10-02 08:19
Hey! I have tested aug firmware and now 2 squirts work simultaneously / alternatively.
4 squirts still not work stops at 23.7 in duty cycle 😢😭

**Comment by noisymime** [comment] 2021-02-22 04:55
Closing as I cannot reproduce on any recent firmware. Please reopen if this is still a problem on master code.

**Closed by noisymime** 2021-02-22 04:55 UTC
