### ISSUE TITLE
Missing INJ pulse with 12-1 cam wheel set at 4 pulses

### ISSUE THREAD

**Issue by Old-Grey6** [noisymime/speeduino#187] opened 2019-01-15 05:32 UTC
For a 4 cyl when set to 12-1 missing tooth Cam speed, 4 INJ pulses Alternating, IGN set on Seq, on the Base Tune, one pulse at TDC is missing on ch#1 - #2 is fine -. Set to 8 cyl and all 4 pulses. Tested on 2 Speedys.
Forum - http://speeduino.com/forum/viewtopic.php?f=11&t=2526
MEGA missing pulse
https://www.mediafire.com/convkey/035e/457dq6iyz41uz0s6g.jpg
video
https://youtu.be/LVXC8l_4zdk

FW - Oct18 
V3.6
Potential engine damage on this setting.

**Comment by noisymime** [comment] 2019-01-15 05:48
Sorry, just saw that you included the channel info.

**Comment by AKCore** [comment] 2019-01-15 05:50
Actually Now that i think on this. A celica with a 1uz and 12 and 1 on paired is doing the same thing since i updated. i was wondering why it was running like crap.

**Comment by noisymime** [comment] 2019-01-15 05:52
Post tunes please. 

More testing, problem only seems to occur when ignition is set to sequential. Set to Wasted spark and it's fine. I'll look into this ASAP

**Comment by noisymime** [comment] 2019-01-15 06:18
Confirmed and resolved. 
Please try latest commit: 1fabf639c5f56a2a6227eb14ed18b09b11388db6

Conditions required to reproduce prior to fix:
* Trigger must be sequential capable
* Ignition must be set to sequential
* Squirts per cycle must be greater than 2

**Comment by Old-Grey6** [comment] 2019-01-15 06:18
[Missing INJ pulse-2019-01-15_17.14.31.zip](https://github.com/noisymime/speeduino/files/2758232/Missing.INJ.pulse-2019-01-15_17.14.31.zip)

**Comment by Old-Grey6** [comment] 2019-01-15 11:09
4 pulses on ch #1 and #2. Will check the rest tomorrow.

**Comment by noisymime** [comment] 2019-01-22 00:40
Closing this one as issue appears resolved

**Closed by noisymime** 2019-01-22 00:40 UTC
Labels: bug
